/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "../Inc/common.h"

extern uint8_t changeLabButtonPressCounter;

extern bool lab1InitDone, lab2InitDone, lab3InitDone;

int main(void) {

	cpuFreqInit(PLL_SOURCE); // configure cpu freq
	sysTickInit(); // configure systick
	changeLabButtonInit();

	for (;;) {

		switch (changeLabButtonPressCounter) {
		case 1: // led strip + button PB12
			if (!lab1InitDone) {

				lab2Deinit();
				lab3Deinit();
				lab1Init();
			}
			lab1Execute();
			break;
		case 2: // 3 leds + pot. ADC1_IN1
			if (!lab2InitDone) {

				lab1Deinit();
				lab3Deinit();
				lab2Init();
			}

			lab2Execute();
			break;
		case 3: // UART + DMA + ADC + temp.sens.
			if (!lab3InitDone) {

				lab1Deinit();
				lab2Deinit();
				lab3Init();
			}

			lab3Execute();
			break;
		}
	}
}
