/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "../Inc/common.h"

extern uint8_t changeLabButtonPressCounter;

extern bool lab1InitDone, lab2InitDone, lab3InitDone; //, potInitDone, uartInitDone, tempSensInitDone, adcInitDone, dmaInitDone;

//extern uint16_t adcFilteredResult[];

int main(void) {

	cpuFreqInit(PLL_SOURCE); // configure cpu freq
	sysTickInit(); // configure systick
	changeLabButtonInit();
//	gpioRccInit(); // configure RCC for GPIOA and GPIOB
//	buttonInit(); // configure button pb12

//	// configure GPIO
//	RCC->AHB1ENR |= (1 << RCC_AHB1ENR_GPIOAEN_Pos);
//	GPIOA->MODER |= (0b10 << GPIO_MODER_MODE8_Pos); // AF for PA8
//	GPIOA->AFR[1] |= (0b0001 << GPIO_AFRH_AFSEL8_Pos); // TIM1_CH1 - AF01
//
//	// configure timer 1
//	RCC->APB2ENR |= (1 << RCC_APB2ENR_TIM1EN_Pos);
//	TIM1->PSC = 1 - 1; // prescaler = 1
//#ifdef HSI_SOURCE
//	TIM1->ARR = ((uint16_t) ((0.000002F * 16000000UL) / 1)); // frequency 500 kHz
//#endif
//#ifdef HSE_SOURCE
//	TIM1->ARR = ((uint16_t) ((0.000002F * 25000000UL) / 1));
//#endif
//#ifdef PLL_SOURCE
//	TIM1->ARR = ((uint16_t) ((0.000002F * 84000000UL) / 1));
//#endif
//	TIM1->CCER |= (1 << TIM_CCER_CC1E_Pos); // CH1 on
//	TIM1->CCMR1 |= (6 << TIM_CCMR1_OC1M_Pos); // direct PWM
//	TIM1->BDTR |= (1 << TIM_BDTR_MOE_Pos); // main output enable
//	TIM1->CR1 |= (1 << TIM_CR1_CEN_Pos); // counter on
//	TIM1->CCR1 = TIM1->ARR / 2; // duty cycle 50%

//	for (uint16_t i = 0; i < (TIM3->ARR * 2); i++) {
//		switch (buttonPressed) {
//		case 0:
//			TIM3->CCR3 =
//					(i < TIM3->ARR) ? i : (TIM3->ARR - (i - TIM3->ARR));
//			break;
//		case 1:
//			TIM3->CCR2 =
//					(i < TIM3->ARR) ? i : (TIM3->ARR - (i - TIM3->ARR));
//			break;
//		case 2:
//			TIM3->CCR1 =
//					(i < TIM3->ARR) ? i : (TIM3->ARR - (i - TIM3->ARR));
//			break;
//		}
//		delayMs(5);
//	}

	for (;;) {

		switch (changeLabButtonPressCounter) {
		case 1: // led strip + button PB12
			if (!lab1InitDone) {

				lab2Deinit();
				lab3Deinit();
				lab1Init();
			}
			lab1Execute();
			break;
		case 2: // 3 leds + pot. ADC1_IN1
			if (!lab2InitDone) {

				lab1Deinit();
				lab3Deinit();
				lab2Init();
			}

 			lab2Execute();
			break;
		case 3: // UART + DMA + ADC + temp.sens.
			if (!lab3InitDone) {

				lab1Deinit();
				lab2Deinit();
				lab3Init();
			}

			lab3Execute();
			break;
//		case 3: // uart + temp. sensor
//			if (!uartInitDone || !tempSensInitDone) {
//
//				ledStripInitDone = false;
//				pwmInitDone = false;
//				potDeInit();
//				adcDeInit(); // temp. sens. is also in adc file
//				dmaDeInit();
//				uartInit();
//				tempSensInit();
//			}
//
//			uartTransmitStr("Tj: ");
//			uartTransmitDec(
//					(int16_t) ((((tempSensGetAverageValue() - 705) * 10) / 25)
//							+ 25));
//			uartTransmitStr("\tT25: ");
//			uartTransmitDec((int16_t) tempSensGetAverageValue());
//			uartTransmitStr("\r\n");
//			break;
//		case 4: // uart + temp. sensor + pot. ADC1_IN1
//			if (!uartInitDone || !adcInitDone || !dmaInitDone) {
//
//				ledStripInitDone = false;
//				pwmInitDone = false;
//				potDeInit();
//				tempSensDeInit();
//				uartInit();
//				adcInit();
//				dmaInit();
//			}
//			adcGetFilteredData();
//			uartTransmitStr("Tj: ");
//			uartTransmitDec(
//					(int16_t) ((((adcFilteredResult[TEMP_SENS] - 705) * 10) / 25)
//							+ 25));
//			uartTransmitStr("\tT25: ");
//			uartTransmitDec(adcFilteredResult[TEMP_SENS]);
//			uartTransmitStr("\tIN1: ");
//			uartTransmitDec(adcFilteredResult[POT]);
//			uartTransmitStr("\r\n");
//			break;
		}
	}
}
